### ISSUE TITLE
Hand and ShapedHand

### ISSUE THREAD

**Issue by tonyday567** [santiweight/haskell-poker#12]
Just saw a comment from you on these names.  

I like `Hole` as the name for the two cards in a players hand, and `Hand` for what you are currently calling `ShapedHand`. I think that's closest to poker jargon.

**Comment by santiweight** [comment]
I agree with `Hand` -> `Hole`. However, I'm not so sure about `Hand` -> `ShapedHand`. In particular, `Hand` is quite an overloaded term in poker I think. It can refer to:
 - a player's 5 card hand at showdown - "what hand do you have? A flush"
 - a player's hole cards
 - a players shaped hole cards
 - a hand history

I personally have come to accept that `Hand` is just too vague to use...

**Comment by tonyday567** [comment]
Ok, fair enough. Their called starting hands also, but that sucks as a name, so ShapedHand is it.

My Enum instance for a ShapedHand:

https://github.com/tonyday567/poker-fold/blob/main/src/Poker/Types.hs#L443

It's convenient, because it slams it into a 13x13 matrix that I am going to use a lot. What do you think?

**Comment by santiweight** [comment]
Hmmm

I’m not sure. It’s definitely not “bad” but it certainly doesn’t make for the cleanest api. I am thinking of tearing out my custom enum instances. 

How about `toGridCoordinate :: ShapedHand -> (Int, Int)` (13x13 coordinates) and the equivalent `from`. I think it would make this functionality more discoverable, and I can’t immediately think reason for using an `Enum` polymorphic function on a `ShapedHand`.

we could also just have both anyway, but this API is better IMO.

**Comment by santiweight** [comment]
Btw what do you think about `ShapedHole`? It strikes me as weird that there is no `Hand`.

**Comment by santiweight** [comment]
Oh - I think I understand now. Your `ShapedHand` is specialised to a `Vector` (I don't know which package is right for this use-case).

I think I want to have that too!

Could we incorporate your version of `Range`, since it is probably way faster and way better memory usage? As long as we have some way to map between the various `Range`s, I would be way happier than what we have in the package right now!

```
newtype ShapedHandRange a = ...
newtype HoleRange a = ...
newtype HandRankRange a = ...

holeToShapedHandRange :: (a -> a -> a) -> HoleRange a -> ShapedHandRange a
-- you get the idea...
```

We could probably get something pretty working with `data family`, but the above addition would be a massive improvement

**Comment by tonyday567** [comment]
Yep, instead of the Map you use.  And sure can! HandRankRange might be too big for what you want (5k or so), but maybe not. It may not be a Vec Bool though - you might be looking for a probability.

**Comment by santiweight** [comment]
Yeah exactly - would you be okay with the polymorphic item type, or do you need that to be specialised also?

**Comment by tonyday567** [comment]
Yep, same thing. Just having the concept in base is enough for me.

**Comment by santiweight** [comment]
Closing in favour of #55
