### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by santiweight** [santiweight/haskell-poker#40]
The final step of our Hackage release process!

**Comment by tonyday567** [comment]
Looks good to me - better than my usual attamepts.

**Comment by santiweight** [comment]
Alright! Pushing to Hackage :)

**Comment by santiweight** [comment]
Yuck - there's still one more problem - the readme doesn't appear to be linking properly for the haddock front page...

**Comment by santiweight** [comment]
Just kidding - it looks fine. Waiting for candidate to process fully...

**Comment by santiweight** [comment]
https://hackage.haskell.org/package/poker-base-0.1.0.0

!!!

**Comment by tonyday567** [comment]
odds are against that, given recency.

**Comment by santiweight** [comment]
Yeah - I deleted message - I realise that's a dumb idea. Also i've personally grown to like `poker-base`.

**Comment by tonyday567** [comment]
yeah, base is very haskelly.

Docs still arent built ...
